name: CI for Next.js site

on:
  # Runs on pushes targeting the main branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]  # You can add more versions here (e.g., 14.x, 18.x)
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: yarn install
        run: yarn install
#      - name: yarn Lint
#        run: yarn lint
      - name: yarn build
        run: yarn build
      - name: Run Tests
        run: yarn test  # Assuming your test script is 'yarn test'
